#! /bin/bash

SSH_AUTH_SOCK_LINK=~/.ssh/ssh_auth_sock.$(hostname -s)

# Fix SSH auth socket location so agent forwarding works with screen.
[ -n "$SSH_AUTH_SOCK" ] && ln -sf $SSH_AUTH_SOCK $SSH_AUTH_SOCK_LINK

# Don't break x11 Forwarding:
# Taken from the sshd(8) manpage.
if read proto cookie && [ -n "$DISPLAY" ]; then
  if [ `echo $DISPLAY | cut -c1-10` = 'localhost:' ]; then
    # X11UseLocalhost=yes
    echo add unix:`echo $DISPLAY | cut -c11-` $proto $cookie
  else
    # X11UseLocalhost=no
    echo add $DISPLAY $proto $cookie
  fi | xauth -q -
fi
