add_newline = false

[character]
success_symbol = '#'
error_symbol = '[#](bold red)'

[cmd_duration]
min_time = 1000
format = '[\($duration\)](bold 33)'

[directory]
style = 'bold underline 34'

[git_branch]
format = '[$symbol$branch]($style) '

[git_status]
ahead = '↑${count}'
behind = '↓${count}'
diverged = '↑${ahead_count}/↓${behind_count}'
untracked = '!'
modified = '↯'
staged = '↺'
format = '[($ahead_behind )](bold fg:141)[($all_status )](bold yellow)'

[hostname]
ssh_only = true
format =  '[$hostname](bold underline 114) '

[jobs]
disabled = false

[line_break]
disabled = false

[status]
map_symbol = false
disabled = false

[username]
format = '[$user]($style) '
style_user = 'yellow'

# languages

[dotnet]
disabled = true

[golang]
disabled = true

[java]
disabled = true

[lua]
disabled = true

[nodejs]
disabled = true

[perl]
disabled = true

[python]
disabled = true

[ruby]
disabled = true
