;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	helm-M-x
	hydra-org-timestamp-change/body
	hydra-org-timestamp-change/lambda-b
	hydra-org-timestamp-change/lambda-f
	hydra-org-timestamp-change/lambda-p
	hydra-org-timestamp-change/nil
	))

(setq mc/cmds-to-run-once
      '(
	))
