;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	helm-M-x
	hydra-multiple-cursors/nil
	hydra-org-timestamp-change/body
	hydra-org-timestamp-change/lambda-b
	hydra-org-timestamp-change/lambda-f
	hydra-org-timestamp-change/lambda-n
	hydra-org-timestamp-change/lambda-p
	hydra-org-timestamp-change/nil
	org-end-of-line
	org-self-insert-command
	))

(setq mc/cmds-to-run-once
      '(
	delete-window
	hydra-multiple-cursors/body
	hydra-multiple-cursors/mc/mark-next-like-this
	))
