;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	dabbrev-expand
	helm-M-x
	hydra-multiple-cursors/nil
	hydra-org-timestamp-change/body
	hydra-org-timestamp-change/lambda-b
	hydra-org-timestamp-change/lambda-f
	hydra-org-timestamp-change/lambda-n
	hydra-org-timestamp-change/lambda-p
	hydra-org-timestamp-change/nil
	hydra-org-timestamp/body
	hydra-org-timestamp/lambda-b
	hydra-org-timestamp/lambda-n
	hydra-org-timestamp/lambda-p
	hydra-org-timestamp/nil
	org-beginning-of-line
	org-cycle
	org-delete-char
	org-end-of-line
	org-kill-line
	org-self-insert-command
	org-time-stamp
	))

(setq mc/cmds-to-run-once
      '(
	delete-window
	hydra-multiple-cursors/body
	hydra-multiple-cursors/mc/mark-next-like-this
	hydra-multiple-cursors/mc/mark-previous-like-this
	hydra-multiple-cursors/mc/unmark-previous-like-this
	org-return
	))
